# Generated by Django 3.0.6 on 2020-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Patinka', 'Patinka'), ('Daugiau nepatinka', 'Daugiau nepatinka')], default='Patinka', max_length=25),
        ),
    ]
